language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'svn+http://svn.edgewall.org/repos/genshi/trunk'; fi

  - "pip install git+git://github.com/TurboGears/backlash.git"
  - "pip install repoze.who"

script: "python setup.py nosetests"
