language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - "pip install git+git://github.com/TurboGears/backlash.git"
  - "pip install repoze.who"
  - "pip install coverage"
  - "pip install nose"
  - "pip install -e .[core-testing]"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls --use-mirrors && export HAS_COVERALLS=1; fi

script: "nosetests -v --with-coverage --cover-package=tg --cover-erase"

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
